### ISSUE TITLE
[Toutes les pages] Rendre le lien Facebook fonctionnel

### ISSUE THREAD

**Issue by alordmg** [vbrizardmg/cliniqueexpression-attente#2]
Le lien vers la page Facebook n'est pas fonctionnel.

Ne pas oublier effet d'hover non plus!

![capture d ecran 2015-06-25 a 3 52 10 pm](https://cloud.githubusercontent.com/assets/11218493/8364182/3461befc-1b52-11e5-8230-5d220ba53263.png)

**Comment by vbrizardmg** [comment]
Il n'y a pas de facebook pour le moment et je ne sais pas s'il va y avoir réellement une page.
À voir !
