### ISSUE TITLE
[Infolettre] Ajuster l'affichage du placeholder ou du input

### ISSUE THREAD

**Issue by alordmg** [vbrizardmg/cliniqueexpression-attente#3]
En ce moment, le placeholder est centré dans le champ mais le input est aligné à gauche.

Personellement je préfère un alignement à gauche, mais si Rachel préfère centrer, il faudrait center aussi le input.

![capture d ecran 2015-06-25 a 3 54 17 pm](https://cloud.githubusercontent.com/assets/11218493/8364208/76863cf4-1b52-11e5-8294-5292d2e235d3.png)

**Comment by vbrizardmg** [comment]
Réglé pour celui-ci.
