### ISSUE TITLE
[Mobile - Accueil] Ajuster l'alignement des éléments d'entête

### ISSUE THREAD

**Issue by alordmg** [vbrizardmg/cliniqueexpression-attente#5]
Le texte du haut devrait avoir une marge équivalente de chaque côté et au dessus.

Le logo Facebook n'est pas bien aligné avec les éléments de menu.

Ça ferait beaucoup plus clean si tous les éléments d'entête étaient bien alignés.

C'est pas grand chose mais ça fait toute la différence!

![capture d ecran 2015-06-25 a 4 01 22 pm](https://cloud.githubusercontent.com/assets/11218493/8364398/06a8f55a-1b54-11e5-9a81-43782f4e1e15.png)

**Comment by vbrizardmg** [comment]
Done, ça devrait marcher :)
