### ISSUE TITLE
[Tablette - Accueil] Alignement des éléments d'entête

### ISSUE THREAD

**Issue by alordmg** [vbrizardmg/cliniqueexpression-attente#7]
Même chose pour tablette!

Texte d'entête + logo Facebook

![capture d ecran 2015-06-25 a 4 21 49 pm](https://cloud.githubusercontent.com/assets/11218493/8364762/99fe0bd6-1b56-11e5-9570-5ba40b0658ce.png)

**Comment by vbrizardmg** [comment]
Problème réglé avec un max-width pour combler l'entre-deux mobile/tablette.
