### ISSUE TITLE
[À propos + Contact] Monter la navigation principale

### ISSUE THREAD

**Issue by alordmg** [vbrizardmg/cliniqueexpression-attente#8]
Quand on passe de la page d'accueil à la page À propos ou Contact, on remarque que la navigation descend un peu.

Étant donné que la navigation est un élément extrêmement important pour l'utilisateur (c'est une façon de savoir où on est, où on peut aller, c'est un bon point de repère) il est important que la navigation se retrouve toujours au même endroit dans toutes les pages.

Ça crée aussi une uniformité et une structure à la page. En ce moment toutes les pages sont très différentes les unes des autres, alors un utilisateur peu expérimenté peut avoir l'impression d'être sur un site complètement différent.

Si c'est trop long/compliqué à régler, on va skipper ça.

![capture d ecran 2015-06-25 a 4 31 16 pm](https://cloud.githubusercontent.com/assets/11218493/8364935/bc3c788a-1b57-11e5-8c54-0c6411d3a1a0.png)

**Comment by vbrizardmg** [comment]
Problème réglé.
Désolé, j'avais pas remarqué ça en ajoutant la phrase sur la page d'accueil.

Thx !

**Comment by alordmg** [comment]
Haha excuse toi pas mec, c'est un projet client rien de personnel ;)
